### ISSUE TITLE
The solution is extremely unclear and very different from the 

### ISSUE THREAD

**Issue by lnhdn** [learn-co-curriculum/dsc-polynomial-regression-lab#1]
and very different from the previous lessons. Please comment your code since I really don't understand what X_plot is or why you need to transform array since they weren't mentioned AT ALL in the lesson.

**Comment by hoffm386** [comment]
Substantially more comments were added in this revision so I'm going to go ahead and close this out https://github.com/learn-co-curriculum/dsc-polynomial-regression-lab/commit/bfa448d8d7a05b754058da5a595cb7536a9c2c49
