### ISSUE TITLE
Saturncloud link going to wrong Jupyter Notebook

### ISSUE THREAD

**Issue by joeldmott** [learn-co-curriculum/dsc-polynomial-regression-lab#3]
## Link to Canvas

The link is the issue, I think it needs to say "index.ipynb" instead of "dataset.ipynb" at the very end, for example:

wrong link:https://w-joelm-ds-course-program-9d208a4bcb304d67846f8e2a874f9c93.flatironschool.saturnenterprise.io/notebooks/workspace/flatiron-curriculum/program/dsc-polynomial-regression-lab/dataset.ipynb

corrected link (at very end of link): https://w-joelm-ds-course-program-9d208a4bcb304d67846f8e2a874f9c93.flatironschool.saturnenterprise.io/notebooks/workspace/flatiron-curriculum/program/dsc-polynomial-regression-lab/index.ipynb

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ x] Other (explain below)

### Source

```
It's just the link as shown above in the "Link to Canvas" part.
```

### Concern

The wrong link just took me to a single code cell that didn't look right.

## (Optional) Proposed Solution

I suppose just replacing the end of the link Saturncloud routes folks to.

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ x] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
thanks for opening this issue :wave:. The Saturn Cloud link has been updated and is opening the index.ipynb file as intended at this time.
